"""
Analyze cross-board noise spectra for interleaved two-channel Data_*.dat files.

The acquisition files are expected to be little-endian int16 samples stored as:

    ch1, ch2, ch1, ch2, ...

The sample rate is the per-channel acquisition rate. The default is 600 MHz.

By default this script compares all four cross-board channel pairs between
Data_1.dat and Data_2.dat:

    Ch1 x Ch1, Ch1 x Ch2, Ch2 x Ch1, Ch2 x Ch2

These are cross-board measurements because each file is generated by a separate board.

For the selected channel pair this script computes Welch averages of:
  - first selected channel PSD
  - second selected channel PSD
  - cross-board spectrum
  - magnitude-squared coherence
  - cross-spectrum phase

Outputs are written next to this script by default.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import firwin, freqz


DEFAULT_DATA_DIR = Path(
    r"C:\Quantum Squeezing\Quantum-Measurement-Software"
    r"\Quantum Measurement UI\bin\Debug\net8.0-windows7.0"
)
DEFAULT_FILES = ("Data_1.dat", "Data_2.dat")
DEFAULT_SAMPLE_RATE_HZ = 600_000_000.0
ALL_CHANNEL_PAIRS = ((1, 1), (1, 2), (2, 1), (2, 2))
DEFAULT_FIR_TAPS = 513


@dataclass
class CrossSpectrumResult:
    label: str
    output_label: str
    signal_a_label: str
    signal_b_label: str
    frequencies_hz: np.ndarray
    psd_a: np.ndarray
    psd_b: np.ndarray
    cross_psd: np.ndarray
    coherence: np.ndarray
    phase_rad: np.ndarray
    segments_used: int
    frames_total: int
    sample_rate_hz: float


@dataclass
class IntegratedBandResult:
    output_label: str
    signal_a_label: str
    signal_b_label: str
    band_low_hz: float
    band_high_hz: float
    fir_taps: int
    integrated_psd_a_counts2: float
    integrated_psd_b_counts2: float
    integrated_cross_real_counts2: float
    integrated_cross_imag_counts2: float
    integrated_cross_abs_counts2: float
    integrated_cross_abs_sum_counts2: float
    integrated_cross_phase_rad: float
    integrated_correlation_magnitude: float


def positive_power_db(values: np.ndarray, floor: float = 1e-300) -> np.ndarray:
    return 10.0 * np.log10(np.maximum(values, floor))


def design_bandpass_fir(
    sample_rate_hz: float,
    *,
    low_fraction: float,
    high_fraction: float,
    num_taps: int,
) -> tuple[np.ndarray, float, float]:
    if num_taps < 3 or num_taps % 2 == 0:
        raise ValueError("--fir-taps must be an odd integer >= 3.")

    band_low_hz = sample_rate_hz * min(low_fraction, high_fraction)
    band_high_hz = sample_rate_hz * max(low_fraction, high_fraction)
    nyquist_hz = sample_rate_hz / 2.0

    if not 0.0 < band_low_hz < band_high_hz < nyquist_hz:
        raise ValueError(
            "FIR band must satisfy 0 < low < high < Nyquist. "
            f"Got {band_low_hz:g} Hz to {band_high_hz:g} Hz with Nyquist {nyquist_hz:g} Hz."
        )

    taps = firwin(
        num_taps,
        [band_low_hz, band_high_hz],
        pass_zero=False,
        fs=sample_rate_hz,
        window="hamming",
    )
    return taps, band_low_hz, band_high_hz


def fir_power_response(
    taps: np.ndarray,
    frequencies_hz: np.ndarray,
    sample_rate_hz: float,
) -> np.ndarray:
    _, response = freqz(taps, worN=frequencies_hz, fs=sample_rate_hz)
    return np.abs(response) ** 2


def integrate_filtered_band(
    result: CrossSpectrumResult,
    taps: np.ndarray,
    band_low_hz: float,
    band_high_hz: float,
) -> IntegratedBandResult:
    power_response = fir_power_response(taps, result.frequencies_hz, result.sample_rate_hz)
    filtered_psd_a = result.psd_a * power_response
    filtered_psd_b = result.psd_b * power_response
    filtered_cross = result.cross_psd * power_response

    band_mask = (result.frequencies_hz >= band_low_hz) & (result.frequencies_hz <= band_high_hz)
    freq = result.frequencies_hz[band_mask]
    if freq.size < 2:
        raise ValueError("Not enough frequency bins inside the requested FIR passband.")

    psd_a_int = float(np.trapezoid(filtered_psd_a[band_mask], freq))
    psd_b_int = float(np.trapezoid(filtered_psd_b[band_mask], freq))
    cross_real_int = float(np.trapezoid(filtered_cross[band_mask].real, freq))
    cross_imag_int = float(np.trapezoid(filtered_cross[band_mask].imag, freq))
    cross_complex = complex(cross_real_int, cross_imag_int)
    cross_abs_int = float(abs(cross_complex))
    cross_abs_sum = float(np.trapezoid(np.abs(filtered_cross[band_mask]), freq))
    denom = max((psd_a_int * psd_b_int) ** 0.5, 1e-300)

    return IntegratedBandResult(
        output_label=result.output_label,
        signal_a_label=result.signal_a_label,
        signal_b_label=result.signal_b_label,
        band_low_hz=band_low_hz,
        band_high_hz=band_high_hz,
        fir_taps=taps.size,
        integrated_psd_a_counts2=psd_a_int,
        integrated_psd_b_counts2=psd_b_int,
        integrated_cross_real_counts2=cross_real_int,
        integrated_cross_imag_counts2=cross_imag_int,
        integrated_cross_abs_counts2=cross_abs_int,
        integrated_cross_abs_sum_counts2=cross_abs_sum,
        integrated_cross_phase_rad=float(np.angle(cross_complex)),
        integrated_correlation_magnitude=float(cross_abs_int / denom),
    )


def read_interleaved_i16(path: Path) -> np.memmap:
    byte_count = path.stat().st_size
    if byte_count % np.dtype("<i2").itemsize != 0:
        raise ValueError(f"{path} byte count is not divisible by int16 size.")

    sample_count = byte_count // np.dtype("<i2").itemsize
    if sample_count < 2 or sample_count % 2 != 0:
        raise ValueError(f"{path} does not contain an even number of int16 samples.")

    raw = np.memmap(path, dtype="<i2", mode="r")
    return raw.reshape((-1, 2))


def compute_cross_board_spectrum(
    path_a: Path,
    path_b: Path,
    *,
    channel_a: int,
    channel_b: int,
    sample_rate_hz: float,
    nperseg: int,
    overlap: float,
    max_segments: int | None,
    remove_mean: bool,
) -> CrossSpectrumResult:
    data_a = read_interleaved_i16(path_a)
    data_b = read_interleaved_i16(path_b)
    frames_total = min(data_a.shape[0], data_b.shape[0])

    if nperseg > frames_total:
        raise ValueError(
            f"nperseg={nperseg} is larger than the available paired "
            f"{frames_total} two-channel frames."
        )

    if not 0.0 <= overlap < 1.0:
        raise ValueError("--overlap must be >= 0 and < 1.")
    if channel_a not in (1, 2) or channel_b not in (1, 2):
        raise ValueError("Channels must be 1 or 2.")

    step = max(1, int(round(nperseg * (1.0 - overlap))))
    window = np.hanning(nperseg).astype(np.float64)
    window_power = np.sum(window * window)
    frequencies_hz = np.fft.rfftfreq(nperseg, d=1.0 / sample_rate_hz)

    pxx = np.zeros(frequencies_hz.size, dtype=np.float64)
    pyy = np.zeros_like(pxx)
    pxy = np.zeros(frequencies_hz.size, dtype=np.complex128)

    starts = range(0, frames_total - nperseg + 1, step)
    segments_used = 0
    idx_a = channel_a - 1
    idx_b = channel_b - 1

    for start in starts:
        sig_a = np.asarray(data_a[start : start + nperseg, idx_a], dtype=np.float64)
        sig_b = np.asarray(data_b[start : start + nperseg, idx_b], dtype=np.float64)

        if remove_mean:
            sig_a = sig_a - np.mean(sig_a)
            sig_b = sig_b - np.mean(sig_b)

        fft_a = np.fft.rfft(sig_a * window)
        fft_b = np.fft.rfft(sig_b * window)

        pxx += np.abs(fft_a) ** 2
        pyy += np.abs(fft_b) ** 2
        pxy += np.conj(fft_a) * fft_b

        segments_used += 1
        if max_segments is not None and segments_used >= max_segments:
            break

    if segments_used == 0:
        raise ValueError("No complete FFT segments were available.")

    scale = 1.0 / (sample_rate_hz * window_power * segments_used)
    pxx *= scale
    pyy *= scale
    pxy *= scale

    if nperseg % 2 == 0:
        one_sided_slice = slice(1, -1)
    else:
        one_sided_slice = slice(1, None)
    pxx[one_sided_slice] *= 2.0
    pyy[one_sided_slice] *= 2.0
    pxy[one_sided_slice] *= 2.0

    coherence = np.abs(pxy) ** 2 / np.maximum(pxx * pyy, 1e-300)
    coherence = np.clip(coherence, 0.0, 1.0)
    phase_rad = np.angle(pxy)

    signal_a_label = f"{path_a.stem} Ch{channel_a}"
    signal_b_label = f"{path_b.stem} Ch{channel_b}"
    label = f"{signal_a_label} x {signal_b_label}"
    output_label = (
        f"{path_a.stem}_ch{channel_a}_x_{path_b.stem}_ch{channel_b}"
    )

    return CrossSpectrumResult(
        label=label,
        output_label=output_label,
        signal_a_label=signal_a_label,
        signal_b_label=signal_b_label,
        frequencies_hz=frequencies_hz,
        psd_a=pxx,
        psd_b=pyy,
        cross_psd=pxy,
        coherence=coherence,
        phase_rad=phase_rad,
        segments_used=segments_used,
        frames_total=frames_total,
        sample_rate_hz=sample_rate_hz,
    )


def save_csv(result: CrossSpectrumResult, output_dir: Path) -> Path:
    csv_path = output_dir / f"{result.output_label}_cross_channel_psd.csv"
    with csv_path.open("w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(
            [
                "frequency_hz",
                "frequency_mhz",
                f"psd_{result.signal_a_label}_counts2_per_hz",
                f"psd_{result.signal_b_label}_counts2_per_hz",
                "cross_psd_real_counts2_per_hz",
                "cross_psd_imag_counts2_per_hz",
                "cross_psd_abs_counts2_per_hz",
                "cross_psd_abs_db_counts2_per_hz",
                "coherence",
                "phase_rad",
            ]
        )
        for idx, freq_hz in enumerate(result.frequencies_hz):
            cross_abs = abs(result.cross_psd[idx])
            writer.writerow(
                [
                    freq_hz,
                    freq_hz / 1e6,
                    result.psd_a[idx],
                    result.psd_b[idx],
                    result.cross_psd[idx].real,
                    result.cross_psd[idx].imag,
                    cross_abs,
                    positive_power_db(np.array([cross_abs]))[0],
                    result.coherence[idx],
                    result.phase_rad[idx],
                ]
            )
    return csv_path


def save_fir_artifacts(
    taps: np.ndarray,
    output_dir: Path,
    sample_rate_hz: float,
    band_low_hz: float,
    band_high_hz: float,
) -> tuple[Path, Path]:
    taps_path = output_dir / "fir_bandpass_fs32_to_fs8_taps.csv"
    with taps_path.open("w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["tap_index", "coefficient"])
        for idx, coefficient in enumerate(taps):
            writer.writerow([idx, coefficient])

    response_freq_hz, response = freqz(taps, worN=8192, fs=sample_rate_hz)
    response_db = 20.0 * np.log10(np.maximum(np.abs(response), 1e-12))

    fig, ax = plt.subplots(figsize=(10, 4), constrained_layout=True)
    ax.plot(response_freq_hz / 1e6, response_db, linewidth=0.9)
    ax.axvspan(band_low_hz / 1e6, band_high_hz / 1e6, alpha=0.18, color="tab:green")
    ax.set_title(
        f"FIR bandpass response: Fs/32 to Fs/8 "
        f"({band_low_hz / 1e6:.3f}-{band_high_hz / 1e6:.3f} MHz)"
    )
    ax.set_xlabel("Frequency (MHz)")
    ax.set_ylabel("Magnitude (dB)")
    ax.grid(True, alpha=0.25)
    ax.set_ylim(-100, 5)
    response_path = output_dir / "fir_bandpass_fs32_to_fs8_response.png"
    fig.savefig(response_path, dpi=180)
    plt.close(fig)
    return taps_path, response_path


def save_integrated_summary(rows: list[IntegratedBandResult], output_dir: Path) -> Path:
    summary_path = output_dir / "cross_board_fir_band_integrated_summary.csv"
    with summary_path.open("w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(
            [
                "pair",
                "signal_a",
                "signal_b",
                "band_low_hz",
                "band_high_hz",
                "fir_taps",
                "integrated_psd_a_counts2",
                "integrated_psd_b_counts2",
                "integrated_cross_real_counts2",
                "integrated_cross_imag_counts2",
                "integrated_cross_abs_counts2",
                "integrated_abs_cross_psd_sum_counts2",
                "integrated_cross_phase_rad",
                "integrated_correlation_magnitude",
            ]
        )
        for row in rows:
            writer.writerow(
                [
                    row.output_label,
                    row.signal_a_label,
                    row.signal_b_label,
                    row.band_low_hz,
                    row.band_high_hz,
                    row.fir_taps,
                    row.integrated_psd_a_counts2,
                    row.integrated_psd_b_counts2,
                    row.integrated_cross_real_counts2,
                    row.integrated_cross_imag_counts2,
                    row.integrated_cross_abs_counts2,
                    row.integrated_cross_abs_sum_counts2,
                    row.integrated_cross_phase_rad,
                    row.integrated_correlation_magnitude,
                ]
            )
    return summary_path


def save_plot(result: CrossSpectrumResult, output_dir: Path) -> Path:
    freq_mhz = result.frequencies_hz / 1e6
    cross_abs = np.abs(result.cross_psd)

    fig, axes = plt.subplots(4, 1, figsize=(13, 10), sharex=True, constrained_layout=True)
    fig.suptitle(
        (
            f"{result.label}: cross-board spectrum "
            f"({result.segments_used} segments, Fs={result.sample_rate_hz / 1e6:.3f} MHz)"
        ),
        fontsize=13,
    )

    axes[0].plot(freq_mhz, positive_power_db(result.psd_a), label=f"{result.signal_a_label} PSD", linewidth=0.8)
    axes[0].plot(freq_mhz, positive_power_db(result.psd_b), label=f"{result.signal_b_label} PSD", linewidth=0.8)
    axes[0].set_ylabel("Auto PSD\n(dB counts^2/Hz)")
    axes[0].grid(True, alpha=0.25)
    axes[0].legend(loc="best")

    axes[1].plot(freq_mhz, positive_power_db(cross_abs), color="tab:green", linewidth=0.8)
    axes[1].set_ylabel("|Cross PSD|\n(dB counts^2/Hz)")
    axes[1].grid(True, alpha=0.25)

    axes[2].plot(freq_mhz, result.coherence, color="tab:red", linewidth=0.8)
    axes[2].set_ylabel("Coherence")
    axes[2].set_ylim(-0.02, 1.02)
    axes[2].grid(True, alpha=0.25)

    axes[3].plot(freq_mhz, result.phase_rad, color="tab:purple", linewidth=0.8)
    axes[3].set_ylabel("Phase\n(rad)")
    axes[3].set_xlabel("Frequency (MHz)")
    axes[3].grid(True, alpha=0.25)

    png_path = output_dir / f"{result.output_label}_cross_channel_psd.png"
    fig.savefig(png_path, dpi=180)
    plt.close(fig)
    return png_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Compute cross-board PSD/coherence for selected channels in interleaved int16 Data_*.dat files."
    )
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    parser.add_argument("--files", nargs=2, default=list(DEFAULT_FILES))
    parser.add_argument(
        "--channels",
        nargs=2,
        type=int,
        default=None,
        help="Analyze one cross-board pair, for example: --channels 1 2. Defaults to all four pairs.",
    )
    parser.add_argument("--output-dir", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument(
        "--sample-rate-hz",
        type=float,
        default=DEFAULT_SAMPLE_RATE_HZ,
        help="Per-channel sample rate used for the frequency axis and PSD scaling.",
    )
    parser.add_argument(
        "--nperseg",
        type=int,
        default=1_048_576,
        help="FFT length in deinterleaved per-channel samples.",
    )
    parser.add_argument("--overlap", type=float, default=0.5)
    parser.add_argument(
        "--max-segments",
        type=int,
        default=None,
        help="Optional limit for fast previews. Omit to average the whole file.",
    )
    parser.add_argument(
        "--keep-dc",
        action="store_true",
        help="Do not subtract each segment mean before the FFT.",
    )
    parser.add_argument(
        "--fir-taps",
        type=int,
        default=DEFAULT_FIR_TAPS,
        help="Odd FIR tap count for the Fs/32 to Fs/8 bandpass integration.",
    )
    parser.add_argument(
        "--disable-fir-integration",
        action="store_true",
        help="Skip FIR design and integrated band-limited summary output.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Data directory: {args.data_dir}")
    print(f"Output directory: {args.output_dir}")
    print(f"Sample rate used for plots/PSD scaling: {args.sample_rate_hz:.6g} Hz")
    integrated_rows: list[IntegratedBandResult] = []

    if args.disable_fir_integration:
        taps = None
        band_low_hz = None
        band_high_hz = None
    else:
        taps, band_low_hz, band_high_hz = design_bandpass_fir(
            args.sample_rate_hz,
            low_fraction=1.0 / 32.0,
            high_fraction=1.0 / 8.0,
            num_taps=args.fir_taps,
        )
        taps_path, response_path = save_fir_artifacts(
            taps,
            args.output_dir,
            args.sample_rate_hz,
            band_low_hz,
            band_high_hz,
        )
        print(
            f"FIR bandpass: {band_low_hz / 1e6:.6g} MHz to "
            f"{band_high_hz / 1e6:.6g} MHz, {args.fir_taps} taps"
        )
        print(f"FIR taps: {taps_path}")
        print(f"FIR response plot: {response_path}")

    path_a = args.data_dir / args.files[0]
    path_b = args.data_dir / args.files[1]
    if not path_a.exists():
        raise FileNotFoundError(path_a)
    if not path_b.exists():
        raise FileNotFoundError(path_b)

    channel_pairs = [tuple(args.channels)] if args.channels is not None else ALL_CHANNEL_PAIRS

    for channel_a, channel_b in channel_pairs:
        print(
            f"\nAnalyzing cross-board pair: "
            f"{path_a.name} Ch{channel_a} x {path_b.name} Ch{channel_b} ..."
        )
        result = compute_cross_board_spectrum(
            path_a,
            path_b,
            channel_a=channel_a,
            channel_b=channel_b,
            sample_rate_hz=args.sample_rate_hz,
            nperseg=args.nperseg,
            overlap=args.overlap,
            max_segments=args.max_segments,
            remove_mean=not args.keep_dc,
        )
        if args.max_segments is not None:
            result.output_label = f"{result.output_label}_preview_{result.segments_used}segments"
        csv_path = save_csv(result, args.output_dir)
        png_path = save_plot(result, args.output_dir)
        if taps is not None and band_low_hz is not None and band_high_hz is not None:
            integrated = integrate_filtered_band(result, taps, band_low_hz, band_high_hz)
            integrated_rows.append(integrated)
            print(
                "  integrated FIR-band |cross|: "
                f"{integrated.integrated_cross_abs_counts2:.6g} counts^2"
            )
            print(
                "  integrated FIR-band corr magnitude: "
                f"{integrated.integrated_correlation_magnitude:.6g}"
            )
        print(f"  paired frames: {result.frames_total:,}")
        print(f"  segments averaged: {result.segments_used:,}")
        print(f"  wrote: {csv_path}")
        print(f"  wrote: {png_path}")

    if integrated_rows:
        summary_path = save_integrated_summary(integrated_rows, args.output_dir)
        print(f"\nIntegrated FIR-band summary: {summary_path}")


if __name__ == "__main__":
    main()
